/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sensores.action;

import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;

import com.sensores.modelo.Celular;
import com.sensores.modelo.Estado;
import com.sensores.modelo.EstadosEP;
import com.sensores.modelo.Sensor;
import com.sensores.persistencia.Persistencia;
import com.sensores.utilidades.Utilidades;

/** 
 * MyEclipse Struts
 * Creation date: 07-05-2008
 * 
 * XDoclet definition:
 * @struts.action path="/alertas" name="alertas" scope="request" validate="true"
 */
public class AlertasAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {		DynaActionForm alertas = (DynaActionForm) form;// TODO Auto-generated method stub
		System.out.println("////////////INICIO ACTION/////////////////");
		if(alertas.get("ep")!=null){
			request.setAttribute("ep", ((Integer)alertas.get("ep")).intValue());
			System.out.println("set ep");
		}
		if(((Integer[])alertas.get("listadoEstados")).length !=0){
			request.setAttribute("listadoEstados", ((Integer[])alertas.get("listadoEstados")));
			System.out.println("set listado Estados");
		}
		Utilidades.cargarListasIniciales(request);
		System.out.println("antes del if opcioncel");
		if (alertas.getString("opcionCel").equals("2")){
			System.out.println("entro al if opcioncel");
			String cel=alertas.getString("celular");
			
			if(!cel.equals("")){
			
				if (Persistencia.existeCelular(cel)){
					//mostrar error "ya exite cel"
					System.out.println("ya exite cel");
				}else{
					Celular celular=new Celular();
					celular.setCelular(cel);
					Persistencia.guardar(celular);
					Utilidades.cargarCelulares(request);
					request.setAttribute("celular", "");
					alertas.set("celular", "");
					System.out.println("se agrego el  cel: " + celular.getCelular());
				}
			}	
		}
		if (alertas.getString("agregar").equals("2")){
			System.out.println("Se agrega la alerta");
			Sensor sensor = Persistencia.cargarSensor(((Integer)alertas.get("ep")).intValue());
						
			Integer[] ids_estados=((Integer[])alertas.get("listadoEstados"));
			List estados=Utilidades.listadoEstadosByID(ids_estados);
					
			Integer[] ids_celulares=((Integer[])alertas.get("listadoCelulares"));
			List celulares=Utilidades.listadoCelularesByID(ids_celulares);
						
			List estadosEPS=Utilidades.convertirListadoEstadosEP(sensor, estados);
			Utilidades.crearAlarmas(celulares,estadosEPS,request);
			request.setAttribute("agregar", "1");
			request.getSession().setAttribute("listadoAlertas", Persistencia.cargarAlertas());
		}
		
		return mapping.findForward("continuar");
	}
}