/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.sensores.action;


import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.action.DynaActionForm;

import com.sensores.persistencia.Persistencia;
import com.sensores.utilidades.Utilidades;

/** 
 * MyEclipse Struts
 * Creation date: 07-10-2008
 * 
 * XDoclet definition:
 * @struts.action path="eliminarAlerta" name="eliminarAlertaForm" scope="request" validate="true"
 * @struts.action-forward name="exito" path="alertas.jsp"
 */
public class EliminarAlertaAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		DynaActionForm eliminarAlertaForm = (DynaActionForm) form;// TODO Auto-generated method stub
		Utilidades.listaEliminarAlertas(request);
		//request.getSession().setAttribute("listadoAlertas", Persistencia.cargarAlertas());
		return mapping.findForward("continuar");
	}
}